### ISSUE TITLE
pathway25y.gmt is reporting image names instead of pathway names with description leading toward the web link

### ISSUE THREAD

**Issue by moonchangin** [diyahir/GeneEmbWebApp#2]
Hi @diyahir 
pathway25y.gmt is reporting image names instead of pathway names. Also, weblink is described in the description.

To replicate this bug:

1. Press "Sample Run" to load in the sample gene list.
2. Choose "pathway25y.gmt" from the available pathways.
3. Press "Run analysis"

<img width="1168" alt="Screen Shot 2021-06-07 at 12 03 01 PM" src="https://user-images.githubusercontent.com/42076449/121061981-28de3e80-c78a-11eb-9403-18ed7ae873c4.png">

**Comment by diyahir** [comment]
This is due to the pathway25.gmt being formatted incorrectly, as I believe it is being worked on currently by a separate team. The way this was generated is that the team took all the figures in all scientific journals and created a gmt file from exacting it’s content (thus the genesets may or may not have a name so the name is just the figure name it came from). That is out of our hands, but thanks for bringing this up!

**Comment by moonchangin** [comment]
Okay thanks!
I will now post issues based on the http://aws2.zhang-lab.org:5000/ for now on.
